language: cpp
compiler:
 - gcc

install:
 - scripts/install-linux.sh

script:
 - ino --help
 - file /usr/local/share/arduino/hardware/tools/g++_arm_none_eabi/bin
 - ls -alF /usr/local/share/arduino/hardware/tools/g++_arm_none_eabi/bin
 - /usr/local/share/arduino/hardware/tools/g++_arm_none_eabi/bin/arm-none-eabi-gcc --version
 - ino build -m mega
